import { useState, useCallback, useRef } from 'react';

/**
 * useDemo — Guided demo tour hook
 * Cycles through steps with auto-advance and optional narration.
 */
const DEMO_STEPS = [
  {
    tab: 'dashboard',
    title: '📊 Dashboard',
    narration: 'Welcome to ChronoLog! Here you can see the AI-powered release summary, version recommendation, and readiness score for this repository.',
    delay: 5000,
  },
  {
    tab: 'categories',
    title: '📂 Categories',
    narration: 'ChronoLog automatically categorizes every commit into features, bug fixes, security patches, performance improvements, breaking changes, and documentation.',
    delay: 5000,
  },
  {
    tab: 'timeline',
    title: '📅 Timeline',
    narration: 'The timeline view shows your commit heatmap — instantly see the most active days, sprint patterns, and project momentum over time.',
    delay: 5000,
  },
  {
    tab: 'mindmap',
    title: '🧠 Mindmap',
    narration: 'This interactive mindmap visualizes how all the changes connect — giving you a birds-eye view of your entire release architecture.',
    delay: 5000,
  },
  {
    tab: 'impact',
    title: '🌍 Impact',
    narration: 'The SDG and Business Impact analyzer shows how your commits affect customer experience, revenue, security, and contribute to UN Sustainable Development Goals.',
    delay: 5000,
  },
  {
    tab: 'risks',
    title: '⚠️ Risk Forecast',
    narration: 'Our AI predicts future errors and technical debt by analyzing commit patterns — giving you a risk score and specific mitigation recommendations.',
    delay: 5000,
  },
  {
    tab: 'stakeholders',
    title: '👥 Stakeholders',
    narration: 'One-click tailored release notes for every audience: developers get technical details, QA gets test guidance, managers get business impact, and users get plain-English explanations.',
    delay: 5000,
  },
  {
    tab: 'story',
    title: '📖 Story',
    narration: 'ChronoLog transforms your dry commit history into a compelling human narrative — perfect for blog posts, release announcements, or team retrospectives.',
    delay: 5000,
  },
  {
    tab: 'share',
    title: '🚀 Share',
    narration: 'Export your analysis as a professional PDF, Markdown report, LinkedIn post, or release email — all generated by AI in seconds.',
    delay: 4000,
  },
];

export const useDemo = ({ setActiveTab, speak, stop }) => {
  const [isRunning, setIsRunning] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [showTooltip, setShowTooltip] = useState(false);
  const timerRef = useRef(null);
  const stepRef = useRef(0);

  const stopDemo = useCallback(() => {
    clearTimeout(timerRef.current);
    stop?.();
    setIsRunning(false);
    setShowTooltip(false);
  }, [stop]);

  const advanceStep = useCallback(
    (stepIndex) => {
      if (stepIndex >= DEMO_STEPS.length) {
        setIsRunning(false);
        setShowTooltip(false);
        return;
      }
      const step = DEMO_STEPS[stepIndex];
      stepRef.current = stepIndex;
      setCurrentStep(stepIndex);
      setActiveTab(step.tab);
      setShowTooltip(true);
      speak?.(step.narration);
      timerRef.current = setTimeout(() => advanceStep(stepIndex + 1), step.delay);
    },
    [setActiveTab, speak]
  );

  const startDemo = useCallback(() => {
    clearTimeout(timerRef.current);
    setIsRunning(true);
    advanceStep(0);
  }, [advanceStep]);

  const currentStepData = DEMO_STEPS[currentStep];

  return {
    isRunning,
    startDemo,
    stopDemo,
    currentStep,
    currentStepData,
    showTooltip,
    totalSteps: DEMO_STEPS.length,
  };
};
