import { useState } from 'react';
import { generateLinkedInPost, generateEmail } from '../services/claude';

const downloadMarkdown = (data) => {
  const { repoInfo, analysis, risks, impact, stakeholders, story, archaeology } = data;
  const content = [
    `# ${repoInfo.name} — ChronoLog Report`,
    `> Generated by ChronoLog on ${new Date().toLocaleDateString()}`,
    '',
    `## 📦 Version: v${analysis?.version?.recommended} (${analysis?.version?.type})`,
    `**Reason:** ${analysis?.version?.reason}`,
    '',
    `## 🤖 AI Summary`,
    analysis?.summary || '',
    '',
    `## 📊 Readiness Score: ${analysis?.readiness?.score}/100 (${analysis?.readiness?.grade})`,
    `**Recommendation:** ${analysis?.readiness?.recommendation}`,
    '',
    '### ✅ Positives',
    ...(analysis?.readiness?.positives?.map(p => `- ${p}`) || []),
    '',
    '### ⚠️ Risks',
    ...(analysis?.readiness?.risks?.map(r => `- ${r}`) || []),
    '',
    `## 📂 Change Categories`,
    `- 🚀 Features: ${analysis?.categories?.features?.length || 0}`,
    `- 🐛 Bug Fixes: ${analysis?.categories?.bugfixes?.length || 0}`,
    `- 🔒 Security: ${analysis?.categories?.security?.length || 0}`,
    `- ⚡ Performance: ${analysis?.categories?.performance?.length || 0}`,
    `- 💥 Breaking: ${analysis?.categories?.breaking?.length || 0}`,
    '',
    `## ⚠️ Risk Forecast: ${risks?.overallRiskLevel?.toUpperCase()} (Score: ${risks?.riskScore}/100)`,
    ...(risks?.predictions?.map(p => `- **${p.area}** (${p.severity}): ${p.risk}`) || []),
    '',
    `## 🌍 Business & SDG Impact`,
    `- Customer Experience: ${impact?.businessImpact?.customerExperience}`,
    `- Revenue Impact: ${impact?.businessImpact?.revenueImpact}`,
    `- Security Impact: ${impact?.businessImpact?.securityImpact}`,
    '',
    impact?.businessImpact?.reasoning || '',
    '',
    `## 👥 Stakeholder Notes`,
    `### 👨‍💻 For Developers`,
    stakeholders?.developer || '',
    '',
    `### 🧪 For QA`,
    stakeholders?.qa || '',
    '',
    `### 📊 For Managers`,
    stakeholders?.manager || '',
    '',
    `### 👤 For Users`,
    stakeholders?.user || '',
    '',
    `## 📖 Release Story`,
    story || '',
    '',
    `## 🏛️ Project History`,
    archaeology || '',
    '',
    `---`,
    `*Generated by [ChronoLog](https://github.com) — Every repo has a story.*`,
  ].join('\n');

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${repoInfo.name}-chronolog-report.md`;
  a.click();
  URL.revokeObjectURL(a.href);
};

const downloadPDF = () => {
  window.print();
};

export default function Share({ data }) {
  const [linkedinPost, setLinkedinPost] = useState('');
  const [emailData, setEmailData] = useState(null);
  const [generating, setGenerating] = useState('');
  const [copied, setCopied] = useState('');
  const [toast, setToast] = useState('');

  const showToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(''), 2500);
  };

  const handleLinkedIn = async () => {
    setGenerating('linkedin');
    try {
      const post = await generateLinkedInPost(
        data.repoInfo.name,
        data.analysis?.summary,
        data.analysis?.version?.recommended
      );
      setLinkedinPost(post);
    } catch (e) {
      showToast('❌ Failed to generate LinkedIn post');
    }
    setGenerating('');
  };

  const handleEmail = async () => {
    setGenerating('email');
    try {
      const result = await generateEmail(
        data.repoInfo.name,
        data.analysis?.summary,
        data.stakeholders,
        data.analysis?.version?.recommended
      );
      setEmailData(result);
    } catch (e) {
      showToast('❌ Failed to generate email');
    }
    setGenerating('');
  };

  const copyText = (text, key) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(key);
      showToast('📋 Copied to clipboard!');
      setTimeout(() => setCopied(''), 2000);
    });
  };

  const openLinkedIn = () => {
    if (!linkedinPost) return;
    copyText(linkedinPost, 'linkedin');
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(`https://github.com/${data.repoInfo.full_name}`)}`, '_blank');
  };

  const openGmail = () => {
    if (!emailData) return;
    window.open(
      `https://mail.google.com/mail/?view=cm&fs=1&su=${encodeURIComponent(emailData.subject)}&body=${encodeURIComponent(emailData.body)}`,
      '_blank'
    );
  };

  return (
    <div style={{ display: 'grid', gap: 20 }}>

      {/* Toast */}
      {toast && <div className="toast animate-fadeInUp">{toast}</div>}

      {/* Export Options */}
      <div className="card animate-fadeInUp" style={{ background: 'linear-gradient(135deg, var(--bg-elevated), rgba(99,102,241,0.08))' }}>
        <div className="card-title">🚀 Export & Share</div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12 }}>
          {[
            {
              icon: '📄', label: 'Markdown Report', sub: 'Full analysis as .md',
              color: '#818cf8', action: () => { downloadMarkdown(data); showToast('✅ Markdown downloaded!'); },
            },
            {
              icon: '🖨️', label: 'PDF Export', sub: 'Print / Save as PDF',
              color: '#34d399', action: () => { showToast('🖨️ Opening print dialog...'); setTimeout(downloadPDF, 300); },
            },
            {
              icon: '💼', label: 'LinkedIn Post', sub: 'AI-generated announcement',
              color: '#60a5fa', action: handleLinkedIn, loading: generating === 'linkedin',
            },
            {
              icon: '📧', label: 'Release Email', sub: 'Professional email draft',
              color: '#f472b6', action: handleEmail, loading: generating === 'email',
            },
          ].map((btn, i) => (
            <button
              key={i}
              onClick={btn.action}
              disabled={!!btn.loading}
              style={{
                padding: '18px 16px', borderRadius: 14, cursor: 'pointer',
                background: btn.loading ? 'rgba(0,0,0,0.2)' : `${btn.color}12`,
                border: `1px solid ${btn.color}30`,
                color: btn.color, transition: 'all 0.2s ease',
                fontFamily: 'inherit', textAlign: 'center',
              }}
              onMouseEnter={(e) => !btn.loading && (e.currentTarget.style.background = `${btn.color}20`, e.currentTarget.style.transform = 'translateY(-2px)')}
              onMouseLeave={(e) => (e.currentTarget.style.background = `${btn.color}12`, e.currentTarget.style.transform = 'none')}
            >
              <div style={{ fontSize: 26, marginBottom: 6 }}>
                {btn.loading ? <span className="spinner" style={{ verticalAlign: 'middle' }} /> : btn.icon}
              </div>
              <div style={{ fontWeight: 700, fontSize: 13 }}>{btn.loading ? 'Generating...' : btn.label}</div>
              <div style={{ fontSize: 11, opacity: 0.7, marginTop: 2 }}>{btn.sub}</div>
            </button>
          ))}
        </div>
      </div>

      {/* LinkedIn Post */}
      {linkedinPost && (
        <div className="card animate-fadeInUp" style={{ background: '#0a1628', border: '1px solid rgba(0,119,181,0.4)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
            <h3 style={{ margin: 0, color: '#0ea5e9', fontSize: 15 }}>💼 LinkedIn Announcement</h3>
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={() => copyText(linkedinPost, 'linkedin')} className="btn btn-ghost" style={{ fontSize: 12 }}>
                {copied === 'linkedin' ? '✅ Copied' : '📋 Copy'}
              </button>
              <button onClick={openLinkedIn} className="btn" style={{ background: '#0077b5', color: 'white', fontSize: 12 }}>
                🚀 Open LinkedIn
              </button>
            </div>
          </div>
          <textarea
            value={linkedinPost}
            onChange={(e) => setLinkedinPost(e.target.value)}
            rows={8}
            style={{
              width: '100%', background: '#0f172a', color: '#e2e8f0',
              border: '1px solid rgba(0,119,181,0.3)', borderRadius: 10,
              padding: 14, fontSize: 14, lineHeight: 1.7, resize: 'vertical',
              boxSizing: 'border-box', fontFamily: 'inherit',
            }}
          />
        </div>
      )}

      {/* Email */}
      {emailData && (
        <div className="card animate-fadeInUp" style={{ background: '#130800', border: '1px solid rgba(234,67,53,0.35)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
            <h3 style={{ margin: 0, color: '#f87171', fontSize: 15 }}>📧 Release Email</h3>
            <button onClick={openGmail} className="btn" style={{ background: '#ea4335', color: 'white', fontSize: 12 }}>
              📧 Open in Gmail
            </button>
          </div>
          <input
            value={emailData.subject}
            onChange={(e) => setEmailData({ ...emailData, subject: e.target.value })}
            style={{
              width: '100%', background: '#0f0800', color: '#e2e8f0',
              border: '1px solid rgba(234,67,53,0.3)', borderRadius: 8,
              padding: '10px 14px', fontSize: 14, marginBottom: 10,
              boxSizing: 'border-box', fontFamily: 'inherit',
            }}
          />
          <textarea
            value={emailData.body}
            onChange={(e) => setEmailData({ ...emailData, body: e.target.value })}
            rows={10}
            style={{
              width: '100%', background: '#0f0800', color: '#e2e8f0',
              border: '1px solid rgba(234,67,53,0.3)', borderRadius: 10,
              padding: 14, fontSize: 14, lineHeight: 1.7, resize: 'vertical',
              boxSizing: 'border-box', fontFamily: 'inherit',
            }}
          />
          <button onClick={() => copyText(emailData.subject + '\n\n' + emailData.body, 'email')} className="btn btn-ghost" style={{ marginTop: 8, fontSize: 12 }}>
            {copied === 'email' ? '✅ Copied!' : '📋 Copy Email'}
          </button>
        </div>
      )}
    </div>
  );
}
